import type { Metadata } from "next";

import { Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  weight: "400",
  subsets: ['latin'], 
  preload: true, 
});

export const metadata: Metadata = {
  title: "RUN GO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${poppins.className} bg-gray-100 min-h-screen`}>{children}</body>
    </html>
  );
}
